### ISSUE TITLE
How do you handle append-only patches?

### ISSUE THREAD

**Issue by michielbdejong** [RubenVerborgh/solid-server-architecture#1]

**Comment by RubenVerborgh** [comment]
That is currently not visualized in the main diagram; the complexities of `PATCH` probably deserve giving it a drawing of its own in the document.

I'll sketch the story I have in mind below, but variations are of course possible.

Background: how patches are applied, depends on the backend. For instance, in a file-based back-end and assuming Turtle, an append-only patch could be implemented by appending to the file (without prior parsing of the rest). In a triplestore-based system, it is an insertion operation.

The classes involved are:
- `Patch` (and subclasses such as `LineBasedPatch`, `RdfPatch`, etc.)
- `ResourceStore` and specifically its `modifyResource(ResourceIdentifier, Patch) : Promise<void>` method
- `Patcher` (and subclasses such as `RdfPatcher`, `AppendTurtlePatcher`, `LineBasedPatcher`)

`Patch` is a data object that describes the patch contents, but does not know how to apply it. It is the result of parsing the request body by a `BodyParser`.

A `ResourceStore` implementation has a list of `Patcher`s (that will likely be specific to the [type of] store). When `modifyResource` is called, it will ask each of the `Patcher`s whether they support the incoming `Patch`. When a supporting one is found, it is ask to apply the patch.

This approach allows for incremental adding of patch functionality. For instance, we can start with implementing a generic `RdfPatcher`, and patching all file types will work. If we later want to add a more efficient append-only patcher for Turtle, we just add an extra class; no other components need to be modified.
