### ISSUE TITLE
Why not checkAccess?

### ISSUE THREAD

**Issue by kjetilk** [RubenVerborgh/solid-server-architecture#22]
Why does the Authorization module not use the `checkAccess` semantics of the acl-check-module? It lead to pretty readable code.

**Comment by RubenVerborgh** [comment]
`Authorizer` works on a higher level; it is not necessarily WAC. For instance, we could plug in a component that (arbitrarily) gives me `write` access to all `.txt` files, or that always allows one user but never another (great for testing).

`checkAccess` would probably be used by `AclBasedAuthorizer`. It has a rather specialized signature and requires quite some knowledge to pass in arguments. I would expect `AclBasedAuthorizer` to receive some of these arguments in its constructor.
