### ISSUE TITLE
What modifications are needed for HTTP/2

### ISSUE THREAD

**Issue by kjetilk** [RubenVerborgh/solid-server-architecture#24]
It seems to me that all modifications that might be needed to support HTTP/2 would be in the HTTP layer. I just wanted to bring it up, because HTTP/2 will be important when dealing with apps that needs to pull data from many sources, and so I think it is important to support it, and therefore important to have it on the radar. :-)

**Comment by RubenVerborgh** [comment]
> It seems to me that all modifications that might be needed to support HTTP/2 would be in the HTTP layer.

I would even reverse that: we should make it so, that all modifications for HTTP/2 remain restricted to the HTTP layer.

**Comment by acoburn** [comment]
> we should make it so, that all modifications for HTTP/2 remain restricted to the HTTP layer.

In my experience, Ruben's assertion is exactly correct. That is also how it works in Trellis: the HTTP server/container layer handles all HTTP/2 protocol interactions while the application layer is entirely insulated from all of those details.

**Comment by RubenVerborgh** [comment]
Resolving this for now; can be reopened if new concerns arrive.
