### ISSUE TITLE
Input filter and validation

### ISSUE THREAD

**Issue by kjetilk** [RubenVerborgh/solid-server-architecture#26]
Where would input filter and validation be plugged in? 

I suppose you could add that to the treatment of Representations, but that's very far down the architecture, and if you're going to reject something (e.g. a malformed ACL), then it is a good practice to do it as early as possible to avoid expend unnecessary physical resources. 

Also, what properties would it have?

**Comment by RubenVerborgh** [comment]
> Where would input filter and validation be plugged in?

It's probably something we need to break down in several cases:
1. validating whether an entire received representation is correct (`PUT`, `POST`)
2. validating whether a patch document makes sense (`PATCH`)
3. validating whether a document makes sense _after_ a patch has been applied

For 1, there's the question of whether a server should accept a syntactically invalid document or not. (There are different consequences.)

For 2, that can happen the moment the `PATCH` is parsed.

For 3, that is interesting, especially if patching should be aborted if we discover the result would be invalid.

**Comment by kjetilk** [comment]
Indeed, there is a very large space here, but I think we need to have this very early. For 1, it is not just syntactic validity, but also if we want to accept stuff that doesn't conform with a shape, it is spam fighting techniques, we might also end up interfacing with YouTube's upload filter :-(

Certain parts of that problem space may need to be shared with 2 and 3 too. 

And, we could end up with pipelines of filters and validators, or trees with dependency injection, or trees or pipelines, where some validators are less important so that we could jump out of the pipeline if it takes too long. 

Stuff like ACL validation needs to be in from day 1, and therefore, it makes sense to have it as a part of the diagram early on too.

**Comment by RubenVerborgh** [comment]
Also see https://github.com/solid/data-interoperability-panel/issues/1

**Comment by RubenVerborgh** [comment]
Resolving this for now as the scope is current LDP+ACL, which does not yet cover validation. Can be reopened the moment it does.
