### ISSUE TITLE
User Admin actions

### ISSUE THREAD

**Issue by kjetilk** [RubenVerborgh/solid-server-architecture#28]
The user needs to have a bunch of actions available to them that lies outside of LDP, like forgotten password, delete my pod, move my pod to a different host.

**Comment by RubenVerborgh** [comment]
Similar answer as #27: there is indeed no diagram detailing this yet.
These would be a different `HttpHandler`.

Additional diagrams might indeed be useful. But I would only draw them if necessary; we can also draft through TypeScript interfaces if there are no major decisions to be taken.

The intention of this repository was not necessarily to be complete, but rather to shed light on difficult/complex parts of the architecture.

**Comment by RubenVerborgh** [comment]
Resolving this for now as the scope is LDP+ACL.
