### ISSUE TITLE
BodyParser produces a ParsedRequestBody, not just any Representation

### ISSUE THREAD

**Issue by michielbdejong** [RubenVerborgh/solid-server-architecture#37]
A ParsedRequestBody is a Representation with a `requiredPermission` field, see https://github.com/inrupt/solid-server-ts/blob/master/src/http/IParsedRequestBody.ts#L9
So https://github.com/RubenVerborgh/solid-server-architecture/blob/master/solid-architecture-v1-2-0.tex#L124 should read 'ParsedRequestBody' instead of 'Representation'

**Comment by RubenVerborgh** [comment]
Resolved with 0d33cdab8dd0d681ac031e1371ecd7bb8796ed80.
