### ISSUE TITLE
Feedback on Quota layer

### ISSUE THREAD

**Issue by rubensworks** [RubenVerborgh/solid-server-architecture#42]
Currently, the Quota layer is a bit vague to me.
Will this touch other layers to block certain operations under certain conditions?

We should also keep in mind the extensibility of this layer. For example, next to storage quota it should (at least architecturally) be possible to add support for restricting the number of R/W operations, track CPU usage, ...
Just making sure things are generic enough :-)

**Comment by RubenVerborgh** [comment]
So the Quota diagram was introduced as a test to see what the impact would be on the architecture of invasive features, such as pod quota management. The idea is that pods (or folders within pods, of the files from a certain app) should remain within a certain size.

> We should also keep in mind the extensibility of this layer. For example, next to storage quota it should (at least architecturally) be possible to add support for restricting the number of R/W operations, track CPU usage, ...

For sure; the idea is rather to show that this feature is possible without deep changes to the base architecture.

**Comment by rubensworks** [comment]
Ok, having it as an impact test makes.

I would've expected to see some kind of bus (in the ResourceStore) at architecture-level that the Quota system could hook into, and listen+intercept resource actions. Such a bus sytem may be required for other systems as well, so we may want to consider including this somewhere in the architecture.

**Comment by RubenVerborgh** [comment]
Instead of a bus, the current architecture opts for a decorator pattern.

What would be the differences/advantages of a bus?
I think it offers more flexibility (and thus complexity) than we need.

**Comment by rubensworks** [comment]
I wasn't aware of the decorator usage, that sounds perfect to me!
If a bus-like system would still be needed in some cases, it should be possible to implement it as a special type of decorator.
