### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by chrisSCM** [RubenVerborgh/solid-server-architecture#43]
Can you provide either an image or short instructions how to make an image from the tex file? Probably a dumb question ;-) but would be nice to have.

**Comment by RubenVerborgh** [comment]
A PDF is at https://rubenverborgh.github.io/solid-server-architecture/solid-architecture-v1-3-0.pdf following the steps at https://github.com/RubenVerborgh/solid-server-architecture/blob/master/.travis.yml, which is what you need to run locally as well.

**Comment by chrisSCM** [comment]
Thank you!
