### ISSUE TITLE
Is this architecture compatible with inrupt's pod-server?

### ISSUE THREAD

**Issue by michielbdejong** [RubenVerborgh/solid-server-architecture#7]
If we compare this architecture with https://github.com/inrupt/wac-ldp#code-structure, are they the same?

Short answer: No, there are two big differences, and a number of tiny ones around naming etc.

Of course, the first question I ask from where I'm sitting, is how can we use this to make https://github.com/inrupt/pod-server and specifically https://github.com/inrupt/wac-ldp better.

## 1) http handlers
I think one big take-away is the idea of using http handlers (middleware-style) instead of a single decision flow as currently in ExecuteTask. That is discussed in https://github.com/inrupt/wac-ldp/issues/77. If we resolve #5 then I think we could make that work, and I do agree that the three special cases we have now for Options, GlobRead,  and ContainerPost, makes the decision flow too complex; a middleware-style code structure would probably fit better there.

But there's more, I think.

## 2) ResourceStore
Looking again at the ResourceStore component here made me realize that it's basically a combination of the RDF and BlobTree components in the current architecture of inrupt's wac-ldp module. So created https://github.com/inrupt/wac-ldp/issues/78 about that, I think that can clear up a lot of confusion!

**Comment by RubenVerborgh** [comment]
> If we compare this architecture with [inrupt/wac-ldp#code-structure](https://github.com/inrupt/wac-ldp#code-structure), are they the same?

To facilitate comparison, we should probably try to get the diagrams in a similar form to the extent possible. Especially the packaging and interfacing are crucial I think for the right understanding. I definitely do not want to drag you into a redrawing agony 🙂, but the reason I chose formal UML is that I wanted to highlight a bunch of important aspect (inheritance, composition, dependencies) for which it was easier to reuse the standard primitives. Several editors exist; I myself prefer the source-based approach of this repository; should you want an introduction, let me know.

> I think one big take-away is the idea of using http handlers (middleware-style) instead of a single decision flow as currently in ExecuteTask.

One other way to do that type of architecture would be “assembly line” style. Simply said, that would like building a hamburger: we have a `TaskList` that starts as empty, and then several tasks are added to it (parse, authentication, authorization, storing, representation) just like an ingredients list. Then the `TaskList` is handled one by one by multiple executors (like one specialized person putting one condiment on a hamburger, as opposed to one person making the whole thing).

That could also work; the downside I think is that you then need a shared data structure, so quite a bit of knowledge. But it is very flexible.

In the architecture I propose, `LdpHandler` knows about each of the required steps. This is less flexible (more uniform hamburger), but the data structures in between are simpler (tomato handler does not know about beef patty).

Pardon the hamburgers, I must be hungry.

> Looking again at the ResourceStore component here made me realize that it's basically a combination of the RDF and BlobTree components in the current architecture of inrupt's wac-ldp module.

That might be indeed; this is definitely where I'd need more detailed information in the architectural diagram to understand what their role is.

The idea behind the `ResourceStore` interface is to expose all needed atomic operations. (So a locking mechanism, for instance, could simply be implemented through a decorator pattern.)

**Comment by RubenVerborgh** [comment]
Will be handled by @acoburn.
