### ISSUE TITLE
Naming change suggestions

### ISSUE THREAD

**Issue by pmcb55** [RubenVerborgh/solid-server-architecture#8]
Just as suggestions, but maybe use 'Iri' instead of ResourceIdentifier?

Also I really like the simplicity of the Trellis interface described here: https://github.com/trellis-ldp/trellis/wiki/Trellis-Architecture.

So I'd suggest the ResourceStore interface use 'get()' instead of 'getRepresentation()', and 'replace()' instead of 'addResource()', 'modifyResource()' and 'deleteResource()').

**Comment by RubenVerborgh** [comment]
> Just as suggestions, but maybe use 'Iri' instead of ResourceIdentifier?

The idea is that `ResourceIdentifier` can have both a public component (IRI) as well as a local component (file path). No very strong opinion though, but yes, an IRI is one kind of `ResourceIdentifier`.

> Also I really like the simplicity of the Trellis interface described here: [trellis-ldp/trellis/wiki/Trellis-Architecture](https://github.com/trellis-ldp/trellis/wiki/Trellis-Architecture).

I do too, except when it comes to the performance of small append patches to a large document 🙂 (cfr. https://github.com/RubenVerborgh/solid-server-architecture/issues/6#issuecomment-490961867)

> So I'd suggest the ResourceStore interface use 'get()' instead of 'getRepresentation()', and 'replace()' instead of 'addResource()', 'modifyResource()' and 'deleteResource()').

Having these allows for optimizations that a `replace` does not allow. But it is perfectly possible for a component to implement the above interface with just `replace`. In fact, we could imagine a `KeyValueResouceStore` abstract base class implementation of `ResourceStore` that translates the interface into a `get`/`replace` abstraction.

**Comment by RubenVerborgh** [comment]
Trellis is now visible in 3c3cd23bd3ef9da48e5272a8dbeb8a28ff029d04.
